# Generated by Django 2.2.13 on 2020-10-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bonds',
            new_name='Bond',
        ),
    ]
